version: "3.2"

services:

  db:
    image: mariadb
    ports:
      - 3308:3306
    volumes:
      - './volumes/db:/var/lib/mysql'
      - './docker/test_db.sql:/docker-entrypoint-initdb.d/test_db.sql'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_app
      MYSQL_PASSWORD: laravel_app_passwd
  
  php:
    build:
      context: .
      dockerfile: DockerfileDev
    container_name: prosperty_recruitment_php81
    volumes:
      - '.:/var/www/html'
    environment:
      - APP_UID=1000
      - APP_GID=1000

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - './src:/var/www/html'
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"